version: '3.8'

services:
  myapp:
    image: myapp:latest
    container_name: spring-app
    ports:
      - "8084:8084"
    depends_on:
      - redis
      - mailhog
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_MAIL_HOST=mailhog
      - SPRING_MAIL_PORT=1025
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8082:8025"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
